package com.google.javascript.jscomp;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.lang.IllegalArgumentException;
import static com.google.javascript.jscomp.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import java.lang.Object;

public class Normalize_addToFront_63661408222 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term626;
     Object term628;
     Object term655;
     Object term682;

    public Normalize_addToFront_63661408222() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        term626 = newInstance(Class.forName("com.google.javascript.jscomp.Normalize"));
        setField(term626, term626.getClass(), "compiler", null);
        setBooleanField(term626, term626.getClass(), "assertOnChange", false);
        term628 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term630 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term632 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term635 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term638 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term641 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term645 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term648 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term651 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term628, term628.getClass(), "type", -1410220680);
        setIntField(term630, term630.getClass(), "type", -1667990367);
        setIntField(term632, term632.getClass(), "type", 0);
        setField(term632, term632.getClass(), "next", null);
        setField(term632, term632.getClass(), "first", null);
        setField(term632, term632.getClass(), "last", null);
        setField(term632, term632.getClass(), "propListHead", null);
        setIntField(term632, term632.getClass(), "sourcePosition", 0);
        setField(term632, term632.getClass(), "jsType", null);
        setField(term632, term632.getClass(), "parent", null);
        setField(term630, term630.getClass(), "next", term632);
        setIntField(term635, term635.getClass(), "type", 0);
        setField(term635, term635.getClass(), "next", null);
        setField(term635, term635.getClass(), "first", null);
        setField(term635, term635.getClass(), "last", null);
        setField(term635, term635.getClass(), "propListHead", null);
        setIntField(term635, term635.getClass(), "sourcePosition", 0);
        setField(term635, term635.getClass(), "jsType", null);
        setField(term635, term635.getClass(), "parent", null);
        setField(term630, term630.getClass(), "first", term635);
        setIntField(term638, term638.getClass(), "type", 0);
        setField(term638, term638.getClass(), "next", null);
        setField(term638, term638.getClass(), "first", null);
        setField(term638, term638.getClass(), "last", null);
        setField(term638, term638.getClass(), "propListHead", null);
        setIntField(term638, term638.getClass(), "sourcePosition", 0);
        setField(term638, term638.getClass(), "jsType", null);
        setField(term638, term638.getClass(), "parent", null);
        setField(term630, term630.getClass(), "last", term638);
        setField(term641, term641.getClass(), "next", null);
        setIntField(term641, term641.getClass(), "type", 0);
        setIntField(term641, term641.getClass(), "intValue", 0);
        setField(term641, term641.getClass(), "objectValue", null);
        setField(term630, term630.getClass(), "propListHead", term641);
        setIntField(term630, term630.getClass(), "sourcePosition", -426764678);
        setField(term630, term630.getClass(), "jsType", null);
        setField(term630, term630.getClass(), "parent", null);
        setField(term628, term628.getClass(), "next", term630);
        setIntField(term645, term645.getClass(), "type", 0);
        setField(term645, term645.getClass(), "next", null);
        setField(term645, term645.getClass(), "first", null);
        setField(term645, term645.getClass(), "last", null);
        setField(term645, term645.getClass(), "propListHead", null);
        setIntField(term645, term645.getClass(), "sourcePosition", 0);
        setField(term645, term645.getClass(), "jsType", null);
        setField(term645, term645.getClass(), "parent", null);
        setField(term628, term628.getClass(), "first", term645);
        setIntField(term648, term648.getClass(), "type", 0);
        setField(term648, term648.getClass(), "next", null);
        setField(term648, term648.getClass(), "first", null);
        setField(term648, term648.getClass(), "last", null);
        setField(term648, term648.getClass(), "propListHead", null);
        setIntField(term648, term648.getClass(), "sourcePosition", 0);
        setField(term648, term648.getClass(), "jsType", null);
        setField(term648, term648.getClass(), "parent", null);
        setField(term628, term628.getClass(), "last", term648);
        setField(term651, term651.getClass(), "next", null);
        setIntField(term651, term651.getClass(), "type", 0);
        setIntField(term651, term651.getClass(), "intValue", 0);
        setField(term651, term651.getClass(), "objectValue", null);
        setField(term628, term628.getClass(), "propListHead", term651);
        setIntField(term628, term628.getClass(), "sourcePosition", -1222614956);
        setField(term628, term628.getClass(), "jsType", null);
        setField(term628, term628.getClass(), "parent", null);
        term655 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term657 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term659 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term662 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term665 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term668 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term672 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term675 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term678 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term655, term655.getClass(), "type", -571169753);
        setIntField(term657, term657.getClass(), "type", 806595993);
        setIntField(term659, term659.getClass(), "type", 0);
        setField(term659, term659.getClass(), "next", null);
        setField(term659, term659.getClass(), "first", null);
        setField(term659, term659.getClass(), "last", null);
        setField(term659, term659.getClass(), "propListHead", null);
        setIntField(term659, term659.getClass(), "sourcePosition", 0);
        setField(term659, term659.getClass(), "jsType", null);
        setField(term659, term659.getClass(), "parent", null);
        setField(term657, term657.getClass(), "next", term659);
        setIntField(term662, term662.getClass(), "type", 0);
        setField(term662, term662.getClass(), "next", null);
        setField(term662, term662.getClass(), "first", null);
        setField(term662, term662.getClass(), "last", null);
        setField(term662, term662.getClass(), "propListHead", null);
        setIntField(term662, term662.getClass(), "sourcePosition", 0);
        setField(term662, term662.getClass(), "jsType", null);
        setField(term662, term662.getClass(), "parent", null);
        setField(term657, term657.getClass(), "first", term662);
        setIntField(term665, term665.getClass(), "type", 0);
        setField(term665, term665.getClass(), "next", null);
        setField(term665, term665.getClass(), "first", null);
        setField(term665, term665.getClass(), "last", null);
        setField(term665, term665.getClass(), "propListHead", null);
        setIntField(term665, term665.getClass(), "sourcePosition", 0);
        setField(term665, term665.getClass(), "jsType", null);
        setField(term665, term665.getClass(), "parent", null);
        setField(term657, term657.getClass(), "last", term665);
        setField(term668, term668.getClass(), "next", null);
        setIntField(term668, term668.getClass(), "type", 0);
        setIntField(term668, term668.getClass(), "intValue", 0);
        setField(term668, term668.getClass(), "objectValue", null);
        setField(term657, term657.getClass(), "propListHead", term668);
        setIntField(term657, term657.getClass(), "sourcePosition", 1694224101);
        setField(term657, term657.getClass(), "jsType", null);
        setField(term657, term657.getClass(), "parent", null);
        setField(term655, term655.getClass(), "next", term657);
        setIntField(term672, term672.getClass(), "type", 0);
        setField(term672, term672.getClass(), "next", null);
        setField(term672, term672.getClass(), "first", null);
        setField(term672, term672.getClass(), "last", null);
        setField(term672, term672.getClass(), "propListHead", null);
        setIntField(term672, term672.getClass(), "sourcePosition", 0);
        setField(term672, term672.getClass(), "jsType", null);
        setField(term672, term672.getClass(), "parent", null);
        setField(term655, term655.getClass(), "first", term672);
        setIntField(term675, term675.getClass(), "type", 0);
        setField(term675, term675.getClass(), "next", null);
        setField(term675, term675.getClass(), "first", null);
        setField(term675, term675.getClass(), "last", null);
        setField(term675, term675.getClass(), "propListHead", null);
        setIntField(term675, term675.getClass(), "sourcePosition", 0);
        setField(term675, term675.getClass(), "jsType", null);
        setField(term675, term675.getClass(), "parent", null);
        setField(term655, term655.getClass(), "last", term675);
        setField(term678, term678.getClass(), "next", null);
        setIntField(term678, term678.getClass(), "type", 0);
        setIntField(term678, term678.getClass(), "intValue", 0);
        setField(term678, term678.getClass(), "objectValue", null);
        setField(term655, term655.getClass(), "propListHead", term678);
        setIntField(term655, term655.getClass(), "sourcePosition", 937859191);
        setField(term655, term655.getClass(), "jsType", null);
        setField(term655, term655.getClass(), "parent", null);
        term682 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term684 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term686 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term689 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term692 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term695 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term699 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term702 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term705 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term682, term682.getClass(), "type", 880977281);
        setIntField(term684, term684.getClass(), "type", -75206835);
        setIntField(term686, term686.getClass(), "type", 0);
        setField(term686, term686.getClass(), "next", null);
        setField(term686, term686.getClass(), "first", null);
        setField(term686, term686.getClass(), "last", null);
        setField(term686, term686.getClass(), "propListHead", null);
        setIntField(term686, term686.getClass(), "sourcePosition", 0);
        setField(term686, term686.getClass(), "jsType", null);
        setField(term686, term686.getClass(), "parent", null);
        setField(term684, term684.getClass(), "next", term686);
        setIntField(term689, term689.getClass(), "type", 0);
        setField(term689, term689.getClass(), "next", null);
        setField(term689, term689.getClass(), "first", null);
        setField(term689, term689.getClass(), "last", null);
        setField(term689, term689.getClass(), "propListHead", null);
        setIntField(term689, term689.getClass(), "sourcePosition", 0);
        setField(term689, term689.getClass(), "jsType", null);
        setField(term689, term689.getClass(), "parent", null);
        setField(term684, term684.getClass(), "first", term689);
        setIntField(term692, term692.getClass(), "type", 0);
        setField(term692, term692.getClass(), "next", null);
        setField(term692, term692.getClass(), "first", null);
        setField(term692, term692.getClass(), "last", null);
        setField(term692, term692.getClass(), "propListHead", null);
        setIntField(term692, term692.getClass(), "sourcePosition", 0);
        setField(term692, term692.getClass(), "jsType", null);
        setField(term692, term692.getClass(), "parent", null);
        setField(term684, term684.getClass(), "last", term692);
        setField(term695, term695.getClass(), "next", null);
        setIntField(term695, term695.getClass(), "type", 0);
        setIntField(term695, term695.getClass(), "intValue", 0);
        setField(term695, term695.getClass(), "objectValue", null);
        setField(term684, term684.getClass(), "propListHead", term695);
        setIntField(term684, term684.getClass(), "sourcePosition", 388157121);
        setField(term684, term684.getClass(), "jsType", null);
        setField(term684, term684.getClass(), "parent", null);
        setField(term682, term682.getClass(), "next", term684);
        setIntField(term699, term699.getClass(), "type", 0);
        setField(term699, term699.getClass(), "next", null);
        setField(term699, term699.getClass(), "first", null);
        setField(term699, term699.getClass(), "last", null);
        setField(term699, term699.getClass(), "propListHead", null);
        setIntField(term699, term699.getClass(), "sourcePosition", 0);
        setField(term699, term699.getClass(), "jsType", null);
        setField(term699, term699.getClass(), "parent", null);
        setField(term682, term682.getClass(), "first", term699);
        setIntField(term702, term702.getClass(), "type", 0);
        setField(term702, term702.getClass(), "next", null);
        setField(term702, term702.getClass(), "first", null);
        setField(term702, term702.getClass(), "last", null);
        setField(term702, term702.getClass(), "propListHead", null);
        setIntField(term702, term702.getClass(), "sourcePosition", 0);
        setField(term702, term702.getClass(), "jsType", null);
        setField(term702, term702.getClass(), "parent", null);
        setField(term682, term682.getClass(), "last", term702);
        setField(term705, term705.getClass(), "next", null);
        setIntField(term705, term705.getClass(), "type", 0);
        setIntField(term705, term705.getClass(), "intValue", 0);
        setField(term705, term705.getClass(), "objectValue", null);
        setField(term682, term682.getClass(), "propListHead", term705);
        setIntField(term682, term682.getClass(), "sourcePosition", 1684998508);
        setField(term682, term682.getClass(), "jsType", null);
        setField(term682, term682.getClass(), "parent", null);
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("com.google.javascript.jscomp.Normalize");
        Class<?>[] argTypes = new Class<?>[3];
        argTypes[0] = Class.forName("com.google.javascript.rhino.Node");
        argTypes[1] = Class.forName("com.google.javascript.rhino.Node");
        argTypes[2] = Class.forName("com.google.javascript.rhino.Node");
        Object[] args = new Object[3];
        args[0] = term628;
        args[1] = term655;
        args[2] = term682;
        try {
            callMethod(klass, "addToFront", argTypes, term626, args);
            assertTrue(false);
        }
        catch (IllegalArgumentException e) {
        }

    }

};


