package com.google.javascript.jscomp;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import static com.google.javascript.jscomp.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import static com.google.javascript.jscomp.EqualityUtils.*;
import java.lang.Object;
import java.util.HashMap;

public class FunctionTypeBuilder_isFunctionTypeDeclaration_1412632693237 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term107612;
     Object term107854;

    public FunctionTypeBuilder_isFunctionTypeDeclaration_1412632693237() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        HashMap term107784 = new HashMap();
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        ((HashMap) term107784).put((Object)null, (Object)null);
        term107612 = newInstance(Class.forName("com.google.javascript.rhino.JSDocInfo"));
        Object term107736 = newInstance(Class.forName("com.google.javascript.rhino.JSDocInfo$LazilyInitializedInfo"));
        setField(term107736, term107736.getClass(), "parameters", term107784);
        setField(term107612, term107612.getClass(), "info", term107736);
        HashMap term107856 = new HashMap();
        term107854 = newInstance(Class.forName("com.google.javascript.rhino.JSDocInfo"));
        Object term107855 = newInstance(Class.forName("com.google.javascript.rhino.JSDocInfo$LazilyInitializedInfo"));
        setField(term107855, term107855.getClass(), "baseType", null);
        setField(term107855, term107855.getClass(), "implementedInterfaces", null);
        setField(term107855, term107855.getClass(), "parameters", term107856);
        setField(term107855, term107855.getClass(), "thrownTypes", null);
        setField(term107855, term107855.getClass(), "templateTypeName", null);
        setField(term107855, term107855.getClass(), "description", null);
        setField(term107855, term107855.getClass(), "deprecated", null);
        setField(term107855, term107855.getClass(), "license", null);
        setField(term107855, term107855.getClass(), "suppressions", null);
        setField(term107854, term107854.getClass(), "info", term107855);
        setField(term107854, term107854.getClass(), "documentation", null);
        setField(term107854, term107854.getClass(), "sourceName", null);
        setField(term107854, term107854.getClass(), "visibility", null);
        setIntField(term107854, term107854.getClass(), "bitset", 0);
        setField(term107854, term107854.getClass(), "type", null);
        setField(term107854, term107854.getClass(), "thisType", null);
        setBooleanField(term107854, term107854.getClass(), "includeDocumentation", false);
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("com.google.javascript.jscomp.FunctionTypeBuilder");
        Class<?>[] argTypes = new Class<?>[1];
        argTypes[0] = Class.forName("com.google.javascript.rhino.JSDocInfo");
        Object[] args = new Object[1];
        args[0] = term107612;
        Object retValue = callMethod(klass, "isFunctionTypeDeclaration", argTypes, null, args);
        assertTrue(recursiveEquals(term107612, term107854));
        assertTrue(recursiveEquals(retValue, true));
    }

};


