package com.google.javascript.jscomp;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import static com.google.javascript.jscomp.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import static com.google.javascript.jscomp.EqualityUtils.*;
import java.lang.Object;
import java.util.ArrayDeque;

public class PeepholeFoldConstants_optimizeSubtree_160650699339 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term1;
     Object term69;
     Object term4727;
     Object term4751;
     Object term4596;

    public PeepholeFoldConstants_optimizeSubtree_160650699339() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        Object term20 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term20, term20.getClass(), "vars", null);
        setField(term20, term20.getClass(), "parent", null);
        setIntField(term20, term20.getClass(), "depth", 0);
        setField(term20, term20.getClass(), "rootNode", null);
        setField(term20, term20.getClass(), "thisType", null);
        setBooleanField(term20, term20.getClass(), "isBottom", false);
        setField(term20, term20.getClass(), "arguments", null);
        Object term23 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term23, term23.getClass(), "vars", null);
        setField(term23, term23.getClass(), "parent", null);
        setIntField(term23, term23.getClass(), "depth", 0);
        setField(term23, term23.getClass(), "rootNode", null);
        setField(term23, term23.getClass(), "thisType", null);
        setBooleanField(term23, term23.getClass(), "isBottom", false);
        setField(term23, term23.getClass(), "arguments", null);
        Object term26 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term26, term26.getClass(), "vars", null);
        setField(term26, term26.getClass(), "parent", null);
        setIntField(term26, term26.getClass(), "depth", 0);
        setField(term26, term26.getClass(), "rootNode", null);
        setField(term26, term26.getClass(), "thisType", null);
        setBooleanField(term26, term26.getClass(), "isBottom", false);
        setField(term26, term26.getClass(), "arguments", null);
        Object term29 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term29, term29.getClass(), "vars", null);
        setField(term29, term29.getClass(), "parent", null);
        setIntField(term29, term29.getClass(), "depth", 0);
        setField(term29, term29.getClass(), "rootNode", null);
        setField(term29, term29.getClass(), "thisType", null);
        setBooleanField(term29, term29.getClass(), "isBottom", false);
        setField(term29, term29.getClass(), "arguments", null);
        Object term32 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term32, term32.getClass(), "vars", null);
        setField(term32, term32.getClass(), "parent", null);
        setIntField(term32, term32.getClass(), "depth", 0);
        setField(term32, term32.getClass(), "rootNode", null);
        setField(term32, term32.getClass(), "thisType", null);
        setBooleanField(term32, term32.getClass(), "isBottom", false);
        setField(term32, term32.getClass(), "arguments", null);
        ArrayDeque term18 = new ArrayDeque();
        ((ArrayDeque) term18).add(term20);
        ((ArrayDeque) term18).add(term23);
        ((ArrayDeque) term18).add(term26);
        ((ArrayDeque) term18).add(term29);
        ((ArrayDeque) term18).add(term32);
        Object term39 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term39, term39.getClass(), "type", 0);
        setField(term39, term39.getClass(), "next", null);
        setField(term39, term39.getClass(), "first", null);
        setField(term39, term39.getClass(), "last", null);
        setField(term39, term39.getClass(), "propListHead", null);
        setIntField(term39, term39.getClass(), "sourcePosition", 0);
        setField(term39, term39.getClass(), "jsType", null);
        setField(term39, term39.getClass(), "parent", null);
        Object term42 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term42, term42.getClass(), "type", 0);
        setField(term42, term42.getClass(), "next", null);
        setField(term42, term42.getClass(), "first", null);
        setField(term42, term42.getClass(), "last", null);
        setField(term42, term42.getClass(), "propListHead", null);
        setIntField(term42, term42.getClass(), "sourcePosition", 0);
        setField(term42, term42.getClass(), "jsType", null);
        setField(term42, term42.getClass(), "parent", null);
        Object term45 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term45, term45.getClass(), "type", 0);
        setField(term45, term45.getClass(), "next", null);
        setField(term45, term45.getClass(), "first", null);
        setField(term45, term45.getClass(), "last", null);
        setField(term45, term45.getClass(), "propListHead", null);
        setIntField(term45, term45.getClass(), "sourcePosition", 0);
        setField(term45, term45.getClass(), "jsType", null);
        setField(term45, term45.getClass(), "parent", null);
        Object term48 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term48, term48.getClass(), "type", 0);
        setField(term48, term48.getClass(), "next", null);
        setField(term48, term48.getClass(), "first", null);
        setField(term48, term48.getClass(), "last", null);
        setField(term48, term48.getClass(), "propListHead", null);
        setIntField(term48, term48.getClass(), "sourcePosition", 0);
        setField(term48, term48.getClass(), "jsType", null);
        setField(term48, term48.getClass(), "parent", null);
        ArrayDeque term37 = new ArrayDeque();
        ((ArrayDeque) term37).add(term39);
        ((ArrayDeque) term37).add(term42);
        ((ArrayDeque) term37).add(term45);
        ((ArrayDeque) term37).add(term48);
        ArrayDeque term53 = new ArrayDeque();
        term1 = newInstance(Class.forName("com.google.javascript.jscomp.PeepholeFoldConstants"));
        Object term2 = newInstance(Class.forName("com.google.javascript.jscomp.NodeTraversal"));
        Object term3 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term5 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term8 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term11 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term14 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setField(term2, term2.getClass(), "compiler", null);
        setField(term2, term2.getClass(), "callback", null);
        setIntField(term3, term3.getClass(), "type", 391863371);
        setIntField(term5, term5.getClass(), "type", 0);
        setField(term5, term5.getClass(), "next", null);
        setField(term5, term5.getClass(), "first", null);
        setField(term5, term5.getClass(), "last", null);
        setField(term5, term5.getClass(), "propListHead", null);
        setIntField(term5, term5.getClass(), "sourcePosition", 0);
        setField(term5, term5.getClass(), "jsType", null);
        setField(term5, term5.getClass(), "parent", null);
        setField(term3, term3.getClass(), "next", term5);
        setIntField(term8, term8.getClass(), "type", 0);
        setField(term8, term8.getClass(), "next", null);
        setField(term8, term8.getClass(), "first", null);
        setField(term8, term8.getClass(), "last", null);
        setField(term8, term8.getClass(), "propListHead", null);
        setIntField(term8, term8.getClass(), "sourcePosition", 0);
        setField(term8, term8.getClass(), "jsType", null);
        setField(term8, term8.getClass(), "parent", null);
        setField(term3, term3.getClass(), "first", term8);
        setIntField(term11, term11.getClass(), "type", 0);
        setField(term11, term11.getClass(), "next", null);
        setField(term11, term11.getClass(), "first", null);
        setField(term11, term11.getClass(), "last", null);
        setField(term11, term11.getClass(), "propListHead", null);
        setIntField(term11, term11.getClass(), "sourcePosition", 0);
        setField(term11, term11.getClass(), "jsType", null);
        setField(term11, term11.getClass(), "parent", null);
        setField(term3, term3.getClass(), "last", term11);
        setField(term14, term14.getClass(), "next", null);
        setIntField(term14, term14.getClass(), "type", 0);
        setIntField(term14, term14.getClass(), "intValue", 0);
        setField(term14, term14.getClass(), "objectValue", null);
        setField(term3, term3.getClass(), "propListHead", term14);
        setIntField(term3, term3.getClass(), "sourcePosition", -1955890973);
        setField(term3, term3.getClass(), "jsType", null);
        setField(term3, term3.getClass(), "parent", null);
        setField(term2, term2.getClass(), "curNode", term3);
        setField(term2, term2.getClass(), "scopes", term18);
        setField(term2, term2.getClass(), "scopeRoots", term37);
        setField(term2, term2.getClass(), "cfgs", term53);
        setField(term2, term2.getClass(), "sourceName", "PAEBtnZtTD");
        setField(term2, term2.getClass(), "scopeCreator", null);
        setField(term2, term2.getClass(), "scopeCallback", null);
        setField(term1, term1.getClass(), "currentTraversal", term2);
        term69 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term71 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term73 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term76 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term79 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term82 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term86 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term89 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term92 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term69, term69.getClass(), "type", 1725571209);
        setIntField(term71, term71.getClass(), "type", 1585847225);
        setIntField(term73, term73.getClass(), "type", 0);
        setField(term73, term73.getClass(), "next", null);
        setField(term73, term73.getClass(), "first", null);
        setField(term73, term73.getClass(), "last", null);
        setField(term73, term73.getClass(), "propListHead", null);
        setIntField(term73, term73.getClass(), "sourcePosition", 0);
        setField(term73, term73.getClass(), "jsType", null);
        setField(term73, term73.getClass(), "parent", null);
        setField(term71, term71.getClass(), "next", term73);
        setIntField(term76, term76.getClass(), "type", 0);
        setField(term76, term76.getClass(), "next", null);
        setField(term76, term76.getClass(), "first", null);
        setField(term76, term76.getClass(), "last", null);
        setField(term76, term76.getClass(), "propListHead", null);
        setIntField(term76, term76.getClass(), "sourcePosition", 0);
        setField(term76, term76.getClass(), "jsType", null);
        setField(term76, term76.getClass(), "parent", null);
        setField(term71, term71.getClass(), "first", term76);
        setIntField(term79, term79.getClass(), "type", 0);
        setField(term79, term79.getClass(), "next", null);
        setField(term79, term79.getClass(), "first", null);
        setField(term79, term79.getClass(), "last", null);
        setField(term79, term79.getClass(), "propListHead", null);
        setIntField(term79, term79.getClass(), "sourcePosition", 0);
        setField(term79, term79.getClass(), "jsType", null);
        setField(term79, term79.getClass(), "parent", null);
        setField(term71, term71.getClass(), "last", term79);
        setField(term82, term82.getClass(), "next", null);
        setIntField(term82, term82.getClass(), "type", 0);
        setIntField(term82, term82.getClass(), "intValue", 0);
        setField(term82, term82.getClass(), "objectValue", null);
        setField(term71, term71.getClass(), "propListHead", term82);
        setIntField(term71, term71.getClass(), "sourcePosition", -1456670397);
        setField(term71, term71.getClass(), "jsType", null);
        setField(term71, term71.getClass(), "parent", null);
        setField(term69, term69.getClass(), "next", term71);
        setIntField(term86, term86.getClass(), "type", 0);
        setField(term86, term86.getClass(), "next", null);
        setField(term86, term86.getClass(), "first", null);
        setField(term86, term86.getClass(), "last", null);
        setField(term86, term86.getClass(), "propListHead", null);
        setIntField(term86, term86.getClass(), "sourcePosition", 0);
        setField(term86, term86.getClass(), "jsType", null);
        setField(term86, term86.getClass(), "parent", null);
        setField(term69, term69.getClass(), "first", term86);
        setIntField(term89, term89.getClass(), "type", 0);
        setField(term89, term89.getClass(), "next", null);
        setField(term89, term89.getClass(), "first", null);
        setField(term89, term89.getClass(), "last", null);
        setField(term89, term89.getClass(), "propListHead", null);
        setIntField(term89, term89.getClass(), "sourcePosition", 0);
        setField(term89, term89.getClass(), "jsType", null);
        setField(term89, term89.getClass(), "parent", null);
        setField(term69, term69.getClass(), "last", term89);
        setField(term92, term92.getClass(), "next", null);
        setIntField(term92, term92.getClass(), "type", 0);
        setIntField(term92, term92.getClass(), "intValue", 0);
        setField(term92, term92.getClass(), "objectValue", null);
        setField(term69, term69.getClass(), "propListHead", term92);
        setIntField(term69, term69.getClass(), "sourcePosition", 1622346318);
        setField(term69, term69.getClass(), "jsType", null);
        setField(term69, term69.getClass(), "parent", null);
        Object term4736 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term4736, term4736.getClass(), "vars", null);
        setField(term4736, term4736.getClass(), "parent", null);
        setIntField(term4736, term4736.getClass(), "depth", 0);
        setField(term4736, term4736.getClass(), "rootNode", null);
        setField(term4736, term4736.getClass(), "thisType", null);
        setBooleanField(term4736, term4736.getClass(), "isBottom", false);
        setField(term4736, term4736.getClass(), "arguments", null);
        Object term4737 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term4737, term4737.getClass(), "vars", null);
        setField(term4737, term4737.getClass(), "parent", null);
        setIntField(term4737, term4737.getClass(), "depth", 0);
        setField(term4737, term4737.getClass(), "rootNode", null);
        setField(term4737, term4737.getClass(), "thisType", null);
        setBooleanField(term4737, term4737.getClass(), "isBottom", false);
        setField(term4737, term4737.getClass(), "arguments", null);
        Object term4738 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term4738, term4738.getClass(), "vars", null);
        setField(term4738, term4738.getClass(), "parent", null);
        setIntField(term4738, term4738.getClass(), "depth", 0);
        setField(term4738, term4738.getClass(), "rootNode", null);
        setField(term4738, term4738.getClass(), "thisType", null);
        setBooleanField(term4738, term4738.getClass(), "isBottom", false);
        setField(term4738, term4738.getClass(), "arguments", null);
        Object term4739 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term4739, term4739.getClass(), "vars", null);
        setField(term4739, term4739.getClass(), "parent", null);
        setIntField(term4739, term4739.getClass(), "depth", 0);
        setField(term4739, term4739.getClass(), "rootNode", null);
        setField(term4739, term4739.getClass(), "thisType", null);
        setBooleanField(term4739, term4739.getClass(), "isBottom", false);
        setField(term4739, term4739.getClass(), "arguments", null);
        Object term4740 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term4740, term4740.getClass(), "vars", null);
        setField(term4740, term4740.getClass(), "parent", null);
        setIntField(term4740, term4740.getClass(), "depth", 0);
        setField(term4740, term4740.getClass(), "rootNode", null);
        setField(term4740, term4740.getClass(), "thisType", null);
        setBooleanField(term4740, term4740.getClass(), "isBottom", false);
        setField(term4740, term4740.getClass(), "arguments", null);
        ArrayDeque term4734 = new ArrayDeque();
        ((ArrayDeque) term4734).add(term4736);
        ((ArrayDeque) term4734).add(term4737);
        ((ArrayDeque) term4734).add(term4738);
        ((ArrayDeque) term4734).add(term4739);
        ((ArrayDeque) term4734).add(term4740);
        Object term4743 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term4743, term4743.getClass(), "type", 0);
        setField(term4743, term4743.getClass(), "next", null);
        setField(term4743, term4743.getClass(), "first", null);
        setField(term4743, term4743.getClass(), "last", null);
        setField(term4743, term4743.getClass(), "propListHead", null);
        setIntField(term4743, term4743.getClass(), "sourcePosition", 0);
        setField(term4743, term4743.getClass(), "jsType", null);
        setField(term4743, term4743.getClass(), "parent", null);
        Object term4744 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term4744, term4744.getClass(), "type", 0);
        setField(term4744, term4744.getClass(), "next", null);
        setField(term4744, term4744.getClass(), "first", null);
        setField(term4744, term4744.getClass(), "last", null);
        setField(term4744, term4744.getClass(), "propListHead", null);
        setIntField(term4744, term4744.getClass(), "sourcePosition", 0);
        setField(term4744, term4744.getClass(), "jsType", null);
        setField(term4744, term4744.getClass(), "parent", null);
        Object term4745 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term4745, term4745.getClass(), "type", 0);
        setField(term4745, term4745.getClass(), "next", null);
        setField(term4745, term4745.getClass(), "first", null);
        setField(term4745, term4745.getClass(), "last", null);
        setField(term4745, term4745.getClass(), "propListHead", null);
        setIntField(term4745, term4745.getClass(), "sourcePosition", 0);
        setField(term4745, term4745.getClass(), "jsType", null);
        setField(term4745, term4745.getClass(), "parent", null);
        Object term4746 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term4746, term4746.getClass(), "type", 0);
        setField(term4746, term4746.getClass(), "next", null);
        setField(term4746, term4746.getClass(), "first", null);
        setField(term4746, term4746.getClass(), "last", null);
        setField(term4746, term4746.getClass(), "propListHead", null);
        setIntField(term4746, term4746.getClass(), "sourcePosition", 0);
        setField(term4746, term4746.getClass(), "jsType", null);
        setField(term4746, term4746.getClass(), "parent", null);
        ArrayDeque term4741 = new ArrayDeque();
        ((ArrayDeque) term4741).add(term4743);
        ((ArrayDeque) term4741).add(term4744);
        ((ArrayDeque) term4741).add(term4745);
        ((ArrayDeque) term4741).add(term4746);
        ArrayDeque term4747 = new ArrayDeque();
        term4727 = newInstance(Class.forName("com.google.javascript.jscomp.PeepholeFoldConstants"));
        Object term4728 = newInstance(Class.forName("com.google.javascript.jscomp.NodeTraversal"));
        Object term4729 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4730 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4731 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4732 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4733 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setField(term4728, term4728.getClass(), "compiler", null);
        setField(term4728, term4728.getClass(), "callback", null);
        setIntField(term4729, term4729.getClass(), "type", 391863371);
        setIntField(term4730, term4730.getClass(), "type", 0);
        setField(term4730, term4730.getClass(), "next", null);
        setField(term4730, term4730.getClass(), "first", null);
        setField(term4730, term4730.getClass(), "last", null);
        setField(term4730, term4730.getClass(), "propListHead", null);
        setIntField(term4730, term4730.getClass(), "sourcePosition", 0);
        setField(term4730, term4730.getClass(), "jsType", null);
        setField(term4730, term4730.getClass(), "parent", null);
        setField(term4729, term4729.getClass(), "next", term4730);
        setIntField(term4731, term4731.getClass(), "type", 0);
        setField(term4731, term4731.getClass(), "next", null);
        setField(term4731, term4731.getClass(), "first", null);
        setField(term4731, term4731.getClass(), "last", null);
        setField(term4731, term4731.getClass(), "propListHead", null);
        setIntField(term4731, term4731.getClass(), "sourcePosition", 0);
        setField(term4731, term4731.getClass(), "jsType", null);
        setField(term4731, term4731.getClass(), "parent", null);
        setField(term4729, term4729.getClass(), "first", term4731);
        setIntField(term4732, term4732.getClass(), "type", 0);
        setField(term4732, term4732.getClass(), "next", null);
        setField(term4732, term4732.getClass(), "first", null);
        setField(term4732, term4732.getClass(), "last", null);
        setField(term4732, term4732.getClass(), "propListHead", null);
        setIntField(term4732, term4732.getClass(), "sourcePosition", 0);
        setField(term4732, term4732.getClass(), "jsType", null);
        setField(term4732, term4732.getClass(), "parent", null);
        setField(term4729, term4729.getClass(), "last", term4732);
        setField(term4733, term4733.getClass(), "next", null);
        setIntField(term4733, term4733.getClass(), "type", 0);
        setIntField(term4733, term4733.getClass(), "intValue", 0);
        setField(term4733, term4733.getClass(), "objectValue", null);
        setField(term4729, term4729.getClass(), "propListHead", term4733);
        setIntField(term4729, term4729.getClass(), "sourcePosition", -1955890973);
        setField(term4729, term4729.getClass(), "jsType", null);
        setField(term4729, term4729.getClass(), "parent", null);
        setField(term4728, term4728.getClass(), "curNode", term4729);
        setField(term4728, term4728.getClass(), "scopes", term4734);
        setField(term4728, term4728.getClass(), "scopeRoots", term4741);
        setField(term4728, term4728.getClass(), "cfgs", term4747);
        setField(term4728, term4728.getClass(), "sourceName", "PAEBtnZtTD");
        setField(term4728, term4728.getClass(), "scopeCreator", null);
        setField(term4728, term4728.getClass(), "scopeCallback", null);
        setField(term4727, term4727.getClass(), "currentTraversal", term4728);
        term4751 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4752 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4753 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4754 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4755 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4756 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term4757 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4758 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4759 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term4751, term4751.getClass(), "type", 1725571209);
        setIntField(term4752, term4752.getClass(), "type", 1585847225);
        setIntField(term4753, term4753.getClass(), "type", 0);
        setField(term4753, term4753.getClass(), "next", null);
        setField(term4753, term4753.getClass(), "first", null);
        setField(term4753, term4753.getClass(), "last", null);
        setField(term4753, term4753.getClass(), "propListHead", null);
        setIntField(term4753, term4753.getClass(), "sourcePosition", 0);
        setField(term4753, term4753.getClass(), "jsType", null);
        setField(term4753, term4753.getClass(), "parent", null);
        setField(term4752, term4752.getClass(), "next", term4753);
        setIntField(term4754, term4754.getClass(), "type", 0);
        setField(term4754, term4754.getClass(), "next", null);
        setField(term4754, term4754.getClass(), "first", null);
        setField(term4754, term4754.getClass(), "last", null);
        setField(term4754, term4754.getClass(), "propListHead", null);
        setIntField(term4754, term4754.getClass(), "sourcePosition", 0);
        setField(term4754, term4754.getClass(), "jsType", null);
        setField(term4754, term4754.getClass(), "parent", null);
        setField(term4752, term4752.getClass(), "first", term4754);
        setIntField(term4755, term4755.getClass(), "type", 0);
        setField(term4755, term4755.getClass(), "next", null);
        setField(term4755, term4755.getClass(), "first", null);
        setField(term4755, term4755.getClass(), "last", null);
        setField(term4755, term4755.getClass(), "propListHead", null);
        setIntField(term4755, term4755.getClass(), "sourcePosition", 0);
        setField(term4755, term4755.getClass(), "jsType", null);
        setField(term4755, term4755.getClass(), "parent", null);
        setField(term4752, term4752.getClass(), "last", term4755);
        setField(term4756, term4756.getClass(), "next", null);
        setIntField(term4756, term4756.getClass(), "type", 0);
        setIntField(term4756, term4756.getClass(), "intValue", 0);
        setField(term4756, term4756.getClass(), "objectValue", null);
        setField(term4752, term4752.getClass(), "propListHead", term4756);
        setIntField(term4752, term4752.getClass(), "sourcePosition", -1456670397);
        setField(term4752, term4752.getClass(), "jsType", null);
        setField(term4752, term4752.getClass(), "parent", null);
        setField(term4751, term4751.getClass(), "next", term4752);
        setIntField(term4757, term4757.getClass(), "type", 0);
        setField(term4757, term4757.getClass(), "next", null);
        setField(term4757, term4757.getClass(), "first", null);
        setField(term4757, term4757.getClass(), "last", null);
        setField(term4757, term4757.getClass(), "propListHead", null);
        setIntField(term4757, term4757.getClass(), "sourcePosition", 0);
        setField(term4757, term4757.getClass(), "jsType", null);
        setField(term4757, term4757.getClass(), "parent", null);
        setField(term4751, term4751.getClass(), "first", term4757);
        setIntField(term4758, term4758.getClass(), "type", 0);
        setField(term4758, term4758.getClass(), "next", null);
        setField(term4758, term4758.getClass(), "first", null);
        setField(term4758, term4758.getClass(), "last", null);
        setField(term4758, term4758.getClass(), "propListHead", null);
        setIntField(term4758, term4758.getClass(), "sourcePosition", 0);
        setField(term4758, term4758.getClass(), "jsType", null);
        setField(term4758, term4758.getClass(), "parent", null);
        setField(term4751, term4751.getClass(), "last", term4758);
        setField(term4759, term4759.getClass(), "next", null);
        setIntField(term4759, term4759.getClass(), "type", 0);
        setIntField(term4759, term4759.getClass(), "intValue", 0);
        setField(term4759, term4759.getClass(), "objectValue", null);
        setField(term4751, term4751.getClass(), "propListHead", term4759);
        setIntField(term4751, term4751.getClass(), "sourcePosition", 1622346318);
        setField(term4751, term4751.getClass(), "jsType", null);
        setField(term4751, term4751.getClass(), "parent", null);
        term4596 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4598 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4600 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4603 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4606 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4609 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term4613 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4616 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term4619 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term4596, term4596.getClass(), "type", 1725571209);
        setIntField(term4598, term4598.getClass(), "type", 1585847225);
        setIntField(term4600, term4600.getClass(), "type", 0);
        setField(term4600, term4600.getClass(), "next", null);
        setField(term4600, term4600.getClass(), "first", null);
        setField(term4600, term4600.getClass(), "last", null);
        setField(term4600, term4600.getClass(), "propListHead", null);
        setIntField(term4600, term4600.getClass(), "sourcePosition", 0);
        setField(term4600, term4600.getClass(), "jsType", null);
        setField(term4600, term4600.getClass(), "parent", null);
        setField(term4598, term4598.getClass(), "next", term4600);
        setIntField(term4603, term4603.getClass(), "type", 0);
        setField(term4603, term4603.getClass(), "next", null);
        setField(term4603, term4603.getClass(), "first", null);
        setField(term4603, term4603.getClass(), "last", null);
        setField(term4603, term4603.getClass(), "propListHead", null);
        setIntField(term4603, term4603.getClass(), "sourcePosition", 0);
        setField(term4603, term4603.getClass(), "jsType", null);
        setField(term4603, term4603.getClass(), "parent", null);
        setField(term4598, term4598.getClass(), "first", term4603);
        setIntField(term4606, term4606.getClass(), "type", 0);
        setField(term4606, term4606.getClass(), "next", null);
        setField(term4606, term4606.getClass(), "first", null);
        setField(term4606, term4606.getClass(), "last", null);
        setField(term4606, term4606.getClass(), "propListHead", null);
        setIntField(term4606, term4606.getClass(), "sourcePosition", 0);
        setField(term4606, term4606.getClass(), "jsType", null);
        setField(term4606, term4606.getClass(), "parent", null);
        setField(term4598, term4598.getClass(), "last", term4606);
        setField(term4609, term4609.getClass(), "next", null);
        setIntField(term4609, term4609.getClass(), "type", 0);
        setIntField(term4609, term4609.getClass(), "intValue", 0);
        setField(term4609, term4609.getClass(), "objectValue", null);
        setField(term4598, term4598.getClass(), "propListHead", term4609);
        setIntField(term4598, term4598.getClass(), "sourcePosition", -1456670397);
        setField(term4598, term4598.getClass(), "jsType", null);
        setField(term4598, term4598.getClass(), "parent", null);
        setField(term4596, term4596.getClass(), "next", term4598);
        setIntField(term4613, term4613.getClass(), "type", 0);
        setField(term4613, term4613.getClass(), "next", null);
        setField(term4613, term4613.getClass(), "first", null);
        setField(term4613, term4613.getClass(), "last", null);
        setField(term4613, term4613.getClass(), "propListHead", null);
        setIntField(term4613, term4613.getClass(), "sourcePosition", 0);
        setField(term4613, term4613.getClass(), "jsType", null);
        setField(term4613, term4613.getClass(), "parent", null);
        setField(term4596, term4596.getClass(), "first", term4613);
        setIntField(term4616, term4616.getClass(), "type", 0);
        setField(term4616, term4616.getClass(), "next", null);
        setField(term4616, term4616.getClass(), "first", null);
        setField(term4616, term4616.getClass(), "last", null);
        setField(term4616, term4616.getClass(), "propListHead", null);
        setIntField(term4616, term4616.getClass(), "sourcePosition", 0);
        setField(term4616, term4616.getClass(), "jsType", null);
        setField(term4616, term4616.getClass(), "parent", null);
        setField(term4596, term4596.getClass(), "last", term4616);
        setField(term4619, term4619.getClass(), "next", null);
        setIntField(term4619, term4619.getClass(), "type", 0);
        setIntField(term4619, term4619.getClass(), "intValue", 0);
        setField(term4619, term4619.getClass(), "objectValue", null);
        setField(term4596, term4596.getClass(), "propListHead", term4619);
        setIntField(term4596, term4596.getClass(), "sourcePosition", 1622346318);
        setField(term4596, term4596.getClass(), "jsType", null);
        setField(term4596, term4596.getClass(), "parent", null);
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("com.google.javascript.jscomp.PeepholeFoldConstants");
        Class<?>[] argTypes = new Class<?>[1];
        argTypes[0] = Class.forName("com.google.javascript.rhino.Node");
        Object[] args = new Object[1];
        args[0] = term69;
        Object retValue = callMethod(klass, "optimizeSubtree", argTypes, term1, args);
        assertTrue(recursiveEquals(term1, term4727));
        assertTrue(recursiveEquals(term69, term4751));
        assertTrue(recursiveEquals(retValue, term4596));
    }

};


