package com.google.javascript.jscomp;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.lang.NullPointerException;
import static com.google.javascript.jscomp.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import java.lang.Object;
import java.util.HashMap;
import java.util.ArrayDeque;

public class DeadAssignmentsElimination_tryRemoveAssignment_13155937818 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term658;
     Object term675;
     Object term742;
     Object term769;
     Object term796;

    public DeadAssignmentsElimination_tryRemoveAssignment_13155937818() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        HashMap term661 = new HashMap();
        term658 = newInstance(Class.forName("com.google.javascript.jscomp.DeadAssignmentsElimination"));
        Object term659 = newInstance(Class.forName("com.google.javascript.jscomp.LiveVariablesAnalysis"));
        Object term660 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        Object term667 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        Object term671 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setField(term658, term658.getClass(), "compiler", null);
        setField(term660, term660.getClass(), "vars", term661);
        setField(term667, term667.getClass(), "vars", null);
        setField(term667, term667.getClass(), "parent", null);
        setIntField(term667, term667.getClass(), "depth", 0);
        setField(term667, term667.getClass(), "rootNode", null);
        setField(term667, term667.getClass(), "thisType", null);
        setBooleanField(term667, term667.getClass(), "isBottom", false);
        setField(term660, term660.getClass(), "parent", term667);
        setIntField(term660, term660.getClass(), "depth", 11724947);
        setIntField(term671, term671.getClass(), "type", 0);
        setField(term671, term671.getClass(), "next", null);
        setField(term671, term671.getClass(), "first", null);
        setField(term671, term671.getClass(), "last", null);
        setField(term671, term671.getClass(), "propListHead", null);
        setIntField(term671, term671.getClass(), "sourcePosition", 0);
        setField(term671, term671.getClass(), "jsType", null);
        setField(term671, term671.getClass(), "parent", null);
        setField(term660, term660.getClass(), "rootNode", term671);
        setField(term660, term660.getClass(), "thisType", null);
        setBooleanField(term660, term660.getClass(), "isBottom", false);
        setField(term659, term659.getClass(), "jsScope", term660);
        setField(term659, term659.getClass(), "escaped", null);
        setField(term659, term659.getClass(), "cfg", null);
        setField(term659, term659.getClass(), "joinOp", null);
        setField(term659, term659.getClass(), "orderedWorkSet", null);
        setField(term658, term658.getClass(), "liveness", term659);
        Object term693 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term693, term693.getClass(), "vars", null);
        setField(term693, term693.getClass(), "parent", null);
        setIntField(term693, term693.getClass(), "depth", 0);
        setField(term693, term693.getClass(), "rootNode", null);
        setField(term693, term693.getClass(), "thisType", null);
        setBooleanField(term693, term693.getClass(), "isBottom", false);
        Object term696 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term696, term696.getClass(), "vars", null);
        setField(term696, term696.getClass(), "parent", null);
        setIntField(term696, term696.getClass(), "depth", 0);
        setField(term696, term696.getClass(), "rootNode", null);
        setField(term696, term696.getClass(), "thisType", null);
        setBooleanField(term696, term696.getClass(), "isBottom", false);
        Object term699 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term699, term699.getClass(), "vars", null);
        setField(term699, term699.getClass(), "parent", null);
        setIntField(term699, term699.getClass(), "depth", 0);
        setField(term699, term699.getClass(), "rootNode", null);
        setField(term699, term699.getClass(), "thisType", null);
        setBooleanField(term699, term699.getClass(), "isBottom", false);
        Object term702 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term702, term702.getClass(), "vars", null);
        setField(term702, term702.getClass(), "parent", null);
        setIntField(term702, term702.getClass(), "depth", 0);
        setField(term702, term702.getClass(), "rootNode", null);
        setField(term702, term702.getClass(), "thisType", null);
        setBooleanField(term702, term702.getClass(), "isBottom", false);
        Object term705 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term705, term705.getClass(), "vars", null);
        setField(term705, term705.getClass(), "parent", null);
        setIntField(term705, term705.getClass(), "depth", 0);
        setField(term705, term705.getClass(), "rootNode", null);
        setField(term705, term705.getClass(), "thisType", null);
        setBooleanField(term705, term705.getClass(), "isBottom", false);
        Object term708 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term708, term708.getClass(), "vars", null);
        setField(term708, term708.getClass(), "parent", null);
        setIntField(term708, term708.getClass(), "depth", 0);
        setField(term708, term708.getClass(), "rootNode", null);
        setField(term708, term708.getClass(), "thisType", null);
        setBooleanField(term708, term708.getClass(), "isBottom", false);
        Object term711 = newInstance(Class.forName("com.google.javascript.jscomp.Scope"));
        setField(term711, term711.getClass(), "vars", null);
        setField(term711, term711.getClass(), "parent", null);
        setIntField(term711, term711.getClass(), "depth", 0);
        setField(term711, term711.getClass(), "rootNode", null);
        setField(term711, term711.getClass(), "thisType", null);
        setBooleanField(term711, term711.getClass(), "isBottom", false);
        ArrayDeque term691 = new ArrayDeque();
        ((ArrayDeque) term691).add(term693);
        ((ArrayDeque) term691).add(term696);
        ((ArrayDeque) term691).add(term699);
        ((ArrayDeque) term691).add(term702);
        ((ArrayDeque) term691).add(term705);
        ((ArrayDeque) term691).add(term708);
        ((ArrayDeque) term691).add(term711);
        Object term718 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term718, term718.getClass(), "type", 0);
        setField(term718, term718.getClass(), "next", null);
        setField(term718, term718.getClass(), "first", null);
        setField(term718, term718.getClass(), "last", null);
        setField(term718, term718.getClass(), "propListHead", null);
        setIntField(term718, term718.getClass(), "sourcePosition", 0);
        setField(term718, term718.getClass(), "jsType", null);
        setField(term718, term718.getClass(), "parent", null);
        Object term721 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        setIntField(term721, term721.getClass(), "type", 0);
        setField(term721, term721.getClass(), "next", null);
        setField(term721, term721.getClass(), "first", null);
        setField(term721, term721.getClass(), "last", null);
        setField(term721, term721.getClass(), "propListHead", null);
        setIntField(term721, term721.getClass(), "sourcePosition", 0);
        setField(term721, term721.getClass(), "jsType", null);
        setField(term721, term721.getClass(), "parent", null);
        ArrayDeque term716 = new ArrayDeque();
        ((ArrayDeque) term716).add(term718);
        ((ArrayDeque) term716).add(term721);
        ArrayDeque term726 = new ArrayDeque();
        term675 = newInstance(Class.forName("com.google.javascript.jscomp.NodeTraversal"));
        Object term676 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term678 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term681 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term684 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term687 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setField(term675, term675.getClass(), "compiler", null);
        setField(term675, term675.getClass(), "callback", null);
        setIntField(term676, term676.getClass(), "type", 1398204340);
        setIntField(term678, term678.getClass(), "type", 0);
        setField(term678, term678.getClass(), "next", null);
        setField(term678, term678.getClass(), "first", null);
        setField(term678, term678.getClass(), "last", null);
        setField(term678, term678.getClass(), "propListHead", null);
        setIntField(term678, term678.getClass(), "sourcePosition", 0);
        setField(term678, term678.getClass(), "jsType", null);
        setField(term678, term678.getClass(), "parent", null);
        setField(term676, term676.getClass(), "next", term678);
        setIntField(term681, term681.getClass(), "type", 0);
        setField(term681, term681.getClass(), "next", null);
        setField(term681, term681.getClass(), "first", null);
        setField(term681, term681.getClass(), "last", null);
        setField(term681, term681.getClass(), "propListHead", null);
        setIntField(term681, term681.getClass(), "sourcePosition", 0);
        setField(term681, term681.getClass(), "jsType", null);
        setField(term681, term681.getClass(), "parent", null);
        setField(term676, term676.getClass(), "first", term681);
        setIntField(term684, term684.getClass(), "type", 0);
        setField(term684, term684.getClass(), "next", null);
        setField(term684, term684.getClass(), "first", null);
        setField(term684, term684.getClass(), "last", null);
        setField(term684, term684.getClass(), "propListHead", null);
        setIntField(term684, term684.getClass(), "sourcePosition", 0);
        setField(term684, term684.getClass(), "jsType", null);
        setField(term684, term684.getClass(), "parent", null);
        setField(term676, term676.getClass(), "last", term684);
        setField(term687, term687.getClass(), "next", null);
        setIntField(term687, term687.getClass(), "type", 0);
        setIntField(term687, term687.getClass(), "intValue", 0);
        setField(term687, term687.getClass(), "objectValue", null);
        setField(term676, term676.getClass(), "propListHead", term687);
        setIntField(term676, term676.getClass(), "sourcePosition", 1384592638);
        setField(term676, term676.getClass(), "jsType", null);
        setField(term676, term676.getClass(), "parent", null);
        setField(term675, term675.getClass(), "curNode", term676);
        setField(term675, term675.getClass(), "scopes", term691);
        setField(term675, term675.getClass(), "scopeRoots", term716);
        setField(term675, term675.getClass(), "cfgs", term726);
        setField(term675, term675.getClass(), "sourceName", "pCTimMblYc");
        setField(term675, term675.getClass(), "scopeCreator", null);
        setField(term675, term675.getClass(), "scopeCallback", null);
        term742 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term744 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term746 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term749 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term752 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term755 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term759 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term762 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term765 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term742, term742.getClass(), "type", 628918458);
        setIntField(term744, term744.getClass(), "type", 663292551);
        setIntField(term746, term746.getClass(), "type", 0);
        setField(term746, term746.getClass(), "next", null);
        setField(term746, term746.getClass(), "first", null);
        setField(term746, term746.getClass(), "last", null);
        setField(term746, term746.getClass(), "propListHead", null);
        setIntField(term746, term746.getClass(), "sourcePosition", 0);
        setField(term746, term746.getClass(), "jsType", null);
        setField(term746, term746.getClass(), "parent", null);
        setField(term744, term744.getClass(), "next", term746);
        setIntField(term749, term749.getClass(), "type", 0);
        setField(term749, term749.getClass(), "next", null);
        setField(term749, term749.getClass(), "first", null);
        setField(term749, term749.getClass(), "last", null);
        setField(term749, term749.getClass(), "propListHead", null);
        setIntField(term749, term749.getClass(), "sourcePosition", 0);
        setField(term749, term749.getClass(), "jsType", null);
        setField(term749, term749.getClass(), "parent", null);
        setField(term744, term744.getClass(), "first", term749);
        setIntField(term752, term752.getClass(), "type", 0);
        setField(term752, term752.getClass(), "next", null);
        setField(term752, term752.getClass(), "first", null);
        setField(term752, term752.getClass(), "last", null);
        setField(term752, term752.getClass(), "propListHead", null);
        setIntField(term752, term752.getClass(), "sourcePosition", 0);
        setField(term752, term752.getClass(), "jsType", null);
        setField(term752, term752.getClass(), "parent", null);
        setField(term744, term744.getClass(), "last", term752);
        setField(term755, term755.getClass(), "next", null);
        setIntField(term755, term755.getClass(), "type", 0);
        setIntField(term755, term755.getClass(), "intValue", 0);
        setField(term755, term755.getClass(), "objectValue", null);
        setField(term744, term744.getClass(), "propListHead", term755);
        setIntField(term744, term744.getClass(), "sourcePosition", -1731761810);
        setField(term744, term744.getClass(), "jsType", null);
        setField(term744, term744.getClass(), "parent", null);
        setField(term742, term742.getClass(), "next", term744);
        setIntField(term759, term759.getClass(), "type", 0);
        setField(term759, term759.getClass(), "next", null);
        setField(term759, term759.getClass(), "first", null);
        setField(term759, term759.getClass(), "last", null);
        setField(term759, term759.getClass(), "propListHead", null);
        setIntField(term759, term759.getClass(), "sourcePosition", 0);
        setField(term759, term759.getClass(), "jsType", null);
        setField(term759, term759.getClass(), "parent", null);
        setField(term742, term742.getClass(), "first", term759);
        setIntField(term762, term762.getClass(), "type", 0);
        setField(term762, term762.getClass(), "next", null);
        setField(term762, term762.getClass(), "first", null);
        setField(term762, term762.getClass(), "last", null);
        setField(term762, term762.getClass(), "propListHead", null);
        setIntField(term762, term762.getClass(), "sourcePosition", 0);
        setField(term762, term762.getClass(), "jsType", null);
        setField(term762, term762.getClass(), "parent", null);
        setField(term742, term742.getClass(), "last", term762);
        setField(term765, term765.getClass(), "next", null);
        setIntField(term765, term765.getClass(), "type", 0);
        setIntField(term765, term765.getClass(), "intValue", 0);
        setField(term765, term765.getClass(), "objectValue", null);
        setField(term742, term742.getClass(), "propListHead", term765);
        setIntField(term742, term742.getClass(), "sourcePosition", 197109649);
        setField(term742, term742.getClass(), "jsType", null);
        setField(term742, term742.getClass(), "parent", null);
        term769 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term771 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term773 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term776 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term779 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term782 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term786 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term789 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term792 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term769, term769.getClass(), "type", 1358829571);
        setIntField(term771, term771.getClass(), "type", -1970452551);
        setIntField(term773, term773.getClass(), "type", 0);
        setField(term773, term773.getClass(), "next", null);
        setField(term773, term773.getClass(), "first", null);
        setField(term773, term773.getClass(), "last", null);
        setField(term773, term773.getClass(), "propListHead", null);
        setIntField(term773, term773.getClass(), "sourcePosition", 0);
        setField(term773, term773.getClass(), "jsType", null);
        setField(term773, term773.getClass(), "parent", null);
        setField(term771, term771.getClass(), "next", term773);
        setIntField(term776, term776.getClass(), "type", 0);
        setField(term776, term776.getClass(), "next", null);
        setField(term776, term776.getClass(), "first", null);
        setField(term776, term776.getClass(), "last", null);
        setField(term776, term776.getClass(), "propListHead", null);
        setIntField(term776, term776.getClass(), "sourcePosition", 0);
        setField(term776, term776.getClass(), "jsType", null);
        setField(term776, term776.getClass(), "parent", null);
        setField(term771, term771.getClass(), "first", term776);
        setIntField(term779, term779.getClass(), "type", 0);
        setField(term779, term779.getClass(), "next", null);
        setField(term779, term779.getClass(), "first", null);
        setField(term779, term779.getClass(), "last", null);
        setField(term779, term779.getClass(), "propListHead", null);
        setIntField(term779, term779.getClass(), "sourcePosition", 0);
        setField(term779, term779.getClass(), "jsType", null);
        setField(term779, term779.getClass(), "parent", null);
        setField(term771, term771.getClass(), "last", term779);
        setField(term782, term782.getClass(), "next", null);
        setIntField(term782, term782.getClass(), "type", 0);
        setIntField(term782, term782.getClass(), "intValue", 0);
        setField(term782, term782.getClass(), "objectValue", null);
        setField(term771, term771.getClass(), "propListHead", term782);
        setIntField(term771, term771.getClass(), "sourcePosition", 114754804);
        setField(term771, term771.getClass(), "jsType", null);
        setField(term771, term771.getClass(), "parent", null);
        setField(term769, term769.getClass(), "next", term771);
        setIntField(term786, term786.getClass(), "type", 0);
        setField(term786, term786.getClass(), "next", null);
        setField(term786, term786.getClass(), "first", null);
        setField(term786, term786.getClass(), "last", null);
        setField(term786, term786.getClass(), "propListHead", null);
        setIntField(term786, term786.getClass(), "sourcePosition", 0);
        setField(term786, term786.getClass(), "jsType", null);
        setField(term786, term786.getClass(), "parent", null);
        setField(term769, term769.getClass(), "first", term786);
        setIntField(term789, term789.getClass(), "type", 0);
        setField(term789, term789.getClass(), "next", null);
        setField(term789, term789.getClass(), "first", null);
        setField(term789, term789.getClass(), "last", null);
        setField(term789, term789.getClass(), "propListHead", null);
        setIntField(term789, term789.getClass(), "sourcePosition", 0);
        setField(term789, term789.getClass(), "jsType", null);
        setField(term789, term789.getClass(), "parent", null);
        setField(term769, term769.getClass(), "last", term789);
        setField(term792, term792.getClass(), "next", null);
        setIntField(term792, term792.getClass(), "type", 0);
        setIntField(term792, term792.getClass(), "intValue", 0);
        setField(term792, term792.getClass(), "objectValue", null);
        setField(term769, term769.getClass(), "propListHead", term792);
        setIntField(term769, term769.getClass(), "sourcePosition", 1687361082);
        setField(term769, term769.getClass(), "jsType", null);
        setField(term769, term769.getClass(), "parent", null);
        term796 = newInstance(Class.forName("com.google.javascript.jscomp.DataFlowAnalysis$FlowState"));
        Object term797 = newInstance(Class.forName("com.google.javascript.jscomp.LiveVariablesAnalysis$LiveVariableLattice"));
        Object term798 = newInstance(Class.forName("java.util.BitSet"));
        long[] term799 = (long[]) newLongArray(1);
        Object term803 = newInstance(Class.forName("com.google.javascript.jscomp.LiveVariablesAnalysis$LiveVariableLattice"));
        Object term804 = newInstance(Class.forName("java.util.BitSet"));
        long[] term805 = (long[]) newLongArray(1);
        setField(term798, term798.getClass(), "words", term799);
        setIntField(term798, term798.getClass(), "wordsInUse", 584893196);
        setBooleanField(term798, term798.getClass(), "sizeIsSticky", true);
        setField(term797, term797.getClass(), "liveSet", term798);
        setField(term796, term796.getClass(), "in", term797);
        setField(term804, term804.getClass(), "words", term805);
        setIntField(term804, term804.getClass(), "wordsInUse", 497269071);
        setBooleanField(term804, term804.getClass(), "sizeIsSticky", true);
        setField(term803, term803.getClass(), "liveSet", term804);
        setField(term796, term796.getClass(), "out", term803);
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("com.google.javascript.jscomp.DeadAssignmentsElimination");
        Class<?>[] argTypes = new Class<?>[4];
        argTypes[0] = Class.forName("com.google.javascript.jscomp.NodeTraversal");
        argTypes[1] = Class.forName("com.google.javascript.rhino.Node");
        argTypes[2] = Class.forName("com.google.javascript.rhino.Node");
        argTypes[3] = Class.forName("com.google.javascript.jscomp.DataFlowAnalysis$FlowState");
        Object[] args = new Object[4];
        args[0] = term675;
        args[1] = term742;
        args[2] = term769;
        args[3] = term796;
        try {
            callMethod(klass, "tryRemoveAssignment", argTypes, term658, args);
            assertTrue(false);
        }
        catch (NullPointerException e) {
        }

    }

};


