package com.google.javascript.jscomp;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import java.lang.NullPointerException;
import static com.google.javascript.jscomp.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import java.lang.String;
import java.lang.Object;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.Collection;
import java.util.HashSet;
import java.util.ArrayList;
import java.util.ArrayDeque;

public class AnalyzePrototypeProperties_process_19476192365 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term31;
     Object term182;
     Object term209;

    public AnalyzePrototypeProperties_process_19476192365() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        Class<? extends Object> term4492 = Class.forName((String) "com.google.javascript.jscomp.AnalyzePrototypeProperties$SymbolType");
        Field term4491 = ((Class) term4492).getDeclaredField((String) "PROPERTY");
        ((Field) term4491).setAccessible(true);
        Object enum5 = ((Field) term4491).get((Object) null);
        HashMap term48 = new HashMap();
        Set<Object> term4852 =  ((Map) term48).keySet();
        HashSet term47 = new HashSet((Collection<? extends Object>) term4852);
        ArrayList term54 = new ArrayList();
        HashMap term58 = new HashMap();
        HashMap term66 = new HashMap();
        Object term75 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term75, term75.getClass(), "elementData", null);
        setIntField(term75, term75.getClass(), "size", -1530420153);
        setIntField(term75, term75.getClass(), "modCount", -469968304);
        Object term78 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term78, term78.getClass(), "elementData", null);
        setIntField(term78, term78.getClass(), "size", -1145578966);
        setIntField(term78, term78.getClass(), "modCount", 679763016);
        ArrayDeque term73 = new ArrayDeque();
        ((ArrayDeque) term73).add(term75);
        ((ArrayDeque) term73).add(term78);
        Object term85 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term85, term85.getClass(), "elementData", null);
        setIntField(term85, term85.getClass(), "size", 1962444399);
        setIntField(term85, term85.getClass(), "modCount", 767834723);
        Object term88 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term88, term88.getClass(), "elementData", null);
        setIntField(term88, term88.getClass(), "size", -602026508);
        setIntField(term88, term88.getClass(), "modCount", -157887805);
        Object term91 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term91, term91.getClass(), "elementData", null);
        setIntField(term91, term91.getClass(), "size", 1876565163);
        setIntField(term91, term91.getClass(), "modCount", -817164822);
        Object term94 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term94, term94.getClass(), "elementData", null);
        setIntField(term94, term94.getClass(), "size", -1016503459);
        setIntField(term94, term94.getClass(), "modCount", -1968847291);
        Object term97 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term97, term97.getClass(), "elementData", null);
        setIntField(term97, term97.getClass(), "size", 579005622);
        setIntField(term97, term97.getClass(), "modCount", -14890619);
        Object term100 = newInstance(Class.forName("com.google.javascript.jscomp.graph.Graph$GraphAnnotationState"));
        setField(term100, term100.getClass(), "elementData", null);
        setIntField(term100, term100.getClass(), "size", 1632125673);
        setIntField(term100, term100.getClass(), "modCount", 454281060);
        ArrayDeque term83 = new ArrayDeque();
        ((ArrayDeque) term83).add(term85);
        ((ArrayDeque) term83).add(term88);
        ((ArrayDeque) term83).add(term91);
        ((ArrayDeque) term83).add(term94);
        ((ArrayDeque) term83).add(term97);
        ((ArrayDeque) term83).add(term100);
        ArrayDeque term136 = new ArrayDeque();
        HashMap term158 = new HashMap();
        HashMap term170 = new HashMap();
        term31 = newInstance(Class.forName("com.google.javascript.jscomp.AnalyzePrototypeProperties"));
        Object term46 = newInstance(Class.forName("com.google.javascript.jscomp.JSModuleGraph"));
        Object term63 = newInstance(Class.forName("com.google.javascript.jscomp.JSModule"));
        Object term65 = newInstance(Class.forName("com.google.javascript.jscomp.graph.LinkedDirectedGraph"));
        Object term105 = newInstance(Class.forName("com.google.javascript.jscomp.AnalyzePrototypeProperties$NameInfo"));
        Object term119 = newInstance(Class.forName("com.google.javascript.jscomp.JSModule"));
        Object term122 = newInstance(Class.forName("com.google.javascript.jscomp.AnalyzePrototypeProperties$NameInfo"));
        Object term140 = newInstance(Class.forName("com.google.javascript.jscomp.JSModule"));
        Object term143 = newInstance(Class.forName("com.google.javascript.jscomp.AnalyzePrototypeProperties$NameInfo"));
        setField(term31, term31.getClass(), "PROPERTY", enum5);
        setField(term31, term31.getClass(), "VAR", enum5);
        setField(term31, term31.getClass(), "compiler", null);
        setBooleanField(term31, term31.getClass(), "canModifyExterns", false);
        setBooleanField(term31, term31.getClass(), "anchorUnusedVars", true);
        setField(term46, term46.getClass(), "modules", term47);
        setField(term46, term46.getClass(), "modulesByDepth", term54);
        setField(term46, term46.getClass(), "dependencyMap", term58);
        setField(term31, term31.getClass(), "moduleGraph", term46);
        setField(term63, term63.getClass(), "name", null);
        setField(term63, term63.getClass(), "inputs", null);
        setField(term63, term63.getClass(), "deps", null);
        setIntField(term63, term63.getClass(), "depth", 0);
        setField(term31, term31.getClass(), "firstModule", term63);
        setField(term65, term65.getClass(), "nodes", term66);
        setBooleanField(term65, term65.getClass(), "useNodeAnnotations", false);
        setBooleanField(term65, term65.getClass(), "useEdgeAnnotations", false);
        setField(term65, term65.getClass(), "nodeAnnotationStack", term73);
        setField(term65, term65.getClass(), "edgeAnnotationStack", term83);
        setField(term31, term31.getClass(), "symbolGraph", term65);
        setField(term105, term105.getClass(), "name", "TJmVBGfTML");
        setBooleanField(term105, term105.getClass(), "referenced", true);
        setField(term105, term105.getClass(), "declarations", null);
        setField(term119, term119.getClass(), "name", null);
        setField(term119, term119.getClass(), "inputs", null);
        setField(term119, term119.getClass(), "deps", null);
        setIntField(term119, term119.getClass(), "depth", 0);
        setField(term105, term105.getClass(), "deepestCommonModuleRef", term119);
        setBooleanField(term105, term105.getClass(), "readClosureVariables", true);
        setField(term105, term105.getClass(), "this$0", null);
        setField(term31, term31.getClass(), "globalNode", term105);
        setField(term122, term122.getClass(), "name", "tPlsykYBqO");
        setBooleanField(term122, term122.getClass(), "referenced", true);
        setField(term122, term122.getClass(), "declarations", term136);
        setField(term140, term140.getClass(), "name", null);
        setField(term140, term140.getClass(), "inputs", null);
        setField(term140, term140.getClass(), "deps", null);
        setIntField(term140, term140.getClass(), "depth", 0);
        setField(term122, term122.getClass(), "deepestCommonModuleRef", term140);
        setBooleanField(term122, term122.getClass(), "readClosureVariables", true);
        setField(term122, term122.getClass(), "this$0", null);
        setField(term31, term31.getClass(), "externNode", term122);
        setField(term143, term143.getClass(), "name", "bLPjGVBhlX");
        setBooleanField(term143, term143.getClass(), "referenced", true);
        setField(term143, term143.getClass(), "declarations", null);
        setField(term143, term143.getClass(), "deepestCommonModuleRef", null);
        setBooleanField(term143, term143.getClass(), "readClosureVariables", false);
        setField(term143, term143.getClass(), "this$0", null);
        setField(term31, term31.getClass(), "anonymousNode", term143);
        setField(term31, term31.getClass(), "propertyNameInfo", term158);
        setField(term31, term31.getClass(), "varNameInfo", term170);
        term182 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term184 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term186 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term189 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term192 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term195 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term199 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term202 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term205 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term182, term182.getClass(), "type", 292681826);
        setIntField(term184, term184.getClass(), "type", 1328271830);
        setIntField(term186, term186.getClass(), "type", 0);
        setField(term186, term186.getClass(), "next", null);
        setField(term186, term186.getClass(), "first", null);
        setField(term186, term186.getClass(), "last", null);
        setField(term186, term186.getClass(), "propListHead", null);
        setIntField(term186, term186.getClass(), "sourcePosition", 0);
        setField(term186, term186.getClass(), "jsType", null);
        setField(term186, term186.getClass(), "parent", null);
        setField(term184, term184.getClass(), "next", term186);
        setIntField(term189, term189.getClass(), "type", 0);
        setField(term189, term189.getClass(), "next", null);
        setField(term189, term189.getClass(), "first", null);
        setField(term189, term189.getClass(), "last", null);
        setField(term189, term189.getClass(), "propListHead", null);
        setIntField(term189, term189.getClass(), "sourcePosition", 0);
        setField(term189, term189.getClass(), "jsType", null);
        setField(term189, term189.getClass(), "parent", null);
        setField(term184, term184.getClass(), "first", term189);
        setIntField(term192, term192.getClass(), "type", 0);
        setField(term192, term192.getClass(), "next", null);
        setField(term192, term192.getClass(), "first", null);
        setField(term192, term192.getClass(), "last", null);
        setField(term192, term192.getClass(), "propListHead", null);
        setIntField(term192, term192.getClass(), "sourcePosition", 0);
        setField(term192, term192.getClass(), "jsType", null);
        setField(term192, term192.getClass(), "parent", null);
        setField(term184, term184.getClass(), "last", term192);
        setField(term195, term195.getClass(), "next", null);
        setIntField(term195, term195.getClass(), "type", 0);
        setIntField(term195, term195.getClass(), "intValue", 0);
        setField(term195, term195.getClass(), "objectValue", null);
        setField(term184, term184.getClass(), "propListHead", term195);
        setIntField(term184, term184.getClass(), "sourcePosition", -1371869594);
        setField(term184, term184.getClass(), "jsType", null);
        setField(term184, term184.getClass(), "parent", null);
        setField(term182, term182.getClass(), "next", term184);
        setIntField(term199, term199.getClass(), "type", 0);
        setField(term199, term199.getClass(), "next", null);
        setField(term199, term199.getClass(), "first", null);
        setField(term199, term199.getClass(), "last", null);
        setField(term199, term199.getClass(), "propListHead", null);
        setIntField(term199, term199.getClass(), "sourcePosition", 0);
        setField(term199, term199.getClass(), "jsType", null);
        setField(term199, term199.getClass(), "parent", null);
        setField(term182, term182.getClass(), "first", term199);
        setIntField(term202, term202.getClass(), "type", 0);
        setField(term202, term202.getClass(), "next", null);
        setField(term202, term202.getClass(), "first", null);
        setField(term202, term202.getClass(), "last", null);
        setField(term202, term202.getClass(), "propListHead", null);
        setIntField(term202, term202.getClass(), "sourcePosition", 0);
        setField(term202, term202.getClass(), "jsType", null);
        setField(term202, term202.getClass(), "parent", null);
        setField(term182, term182.getClass(), "last", term202);
        setField(term205, term205.getClass(), "next", null);
        setIntField(term205, term205.getClass(), "type", 0);
        setIntField(term205, term205.getClass(), "intValue", 0);
        setField(term205, term205.getClass(), "objectValue", null);
        setField(term182, term182.getClass(), "propListHead", term205);
        setIntField(term182, term182.getClass(), "sourcePosition", -2095575670);
        setField(term182, term182.getClass(), "jsType", null);
        setField(term182, term182.getClass(), "parent", null);
        term209 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term211 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term213 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term216 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term219 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term222 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        Object term226 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term229 = newInstance(Class.forName("com.google.javascript.rhino.Node"));
        Object term232 = newInstance(Class.forName("com.google.javascript.rhino.Node$PropListItem"));
        setIntField(term209, term209.getClass(), "type", -93135961);
        setIntField(term211, term211.getClass(), "type", 962840079);
        setIntField(term213, term213.getClass(), "type", 0);
        setField(term213, term213.getClass(), "next", null);
        setField(term213, term213.getClass(), "first", null);
        setField(term213, term213.getClass(), "last", null);
        setField(term213, term213.getClass(), "propListHead", null);
        setIntField(term213, term213.getClass(), "sourcePosition", 0);
        setField(term213, term213.getClass(), "jsType", null);
        setField(term213, term213.getClass(), "parent", null);
        setField(term211, term211.getClass(), "next", term213);
        setIntField(term216, term216.getClass(), "type", 0);
        setField(term216, term216.getClass(), "next", null);
        setField(term216, term216.getClass(), "first", null);
        setField(term216, term216.getClass(), "last", null);
        setField(term216, term216.getClass(), "propListHead", null);
        setIntField(term216, term216.getClass(), "sourcePosition", 0);
        setField(term216, term216.getClass(), "jsType", null);
        setField(term216, term216.getClass(), "parent", null);
        setField(term211, term211.getClass(), "first", term216);
        setIntField(term219, term219.getClass(), "type", 0);
        setField(term219, term219.getClass(), "next", null);
        setField(term219, term219.getClass(), "first", null);
        setField(term219, term219.getClass(), "last", null);
        setField(term219, term219.getClass(), "propListHead", null);
        setIntField(term219, term219.getClass(), "sourcePosition", 0);
        setField(term219, term219.getClass(), "jsType", null);
        setField(term219, term219.getClass(), "parent", null);
        setField(term211, term211.getClass(), "last", term219);
        setField(term222, term222.getClass(), "next", null);
        setIntField(term222, term222.getClass(), "type", 0);
        setIntField(term222, term222.getClass(), "intValue", 0);
        setField(term222, term222.getClass(), "objectValue", null);
        setField(term211, term211.getClass(), "propListHead", term222);
        setIntField(term211, term211.getClass(), "sourcePosition", 335112684);
        setField(term211, term211.getClass(), "jsType", null);
        setField(term211, term211.getClass(), "parent", null);
        setField(term209, term209.getClass(), "next", term211);
        setIntField(term226, term226.getClass(), "type", 0);
        setField(term226, term226.getClass(), "next", null);
        setField(term226, term226.getClass(), "first", null);
        setField(term226, term226.getClass(), "last", null);
        setField(term226, term226.getClass(), "propListHead", null);
        setIntField(term226, term226.getClass(), "sourcePosition", 0);
        setField(term226, term226.getClass(), "jsType", null);
        setField(term226, term226.getClass(), "parent", null);
        setField(term209, term209.getClass(), "first", term226);
        setIntField(term229, term229.getClass(), "type", 0);
        setField(term229, term229.getClass(), "next", null);
        setField(term229, term229.getClass(), "first", null);
        setField(term229, term229.getClass(), "last", null);
        setField(term229, term229.getClass(), "propListHead", null);
        setIntField(term229, term229.getClass(), "sourcePosition", 0);
        setField(term229, term229.getClass(), "jsType", null);
        setField(term229, term229.getClass(), "parent", null);
        setField(term209, term209.getClass(), "last", term229);
        setField(term232, term232.getClass(), "next", null);
        setIntField(term232, term232.getClass(), "type", 0);
        setIntField(term232, term232.getClass(), "intValue", 0);
        setField(term232, term232.getClass(), "objectValue", null);
        setField(term209, term209.getClass(), "propListHead", term232);
        setIntField(term209, term209.getClass(), "sourcePosition", 1551099402);
        setField(term209, term209.getClass(), "jsType", null);
        setField(term209, term209.getClass(), "parent", null);
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("com.google.javascript.jscomp.AnalyzePrototypeProperties");
        Class<?>[] argTypes = new Class<?>[2];
        argTypes[0] = Class.forName("com.google.javascript.rhino.Node");
        argTypes[1] = Class.forName("com.google.javascript.rhino.Node");
        Object[] args = new Object[2];
        args[0] = term182;
        args[1] = term209;
        try {
            callMethod(klass, "process", argTypes, term31, args);
            assertTrue(false);
        }
        catch (NullPointerException e) {
        }

    }

};


