package org.apache.commons.collections.map;

import java.lang.Throwable;
import java.lang.IllegalStateException;
import org.junit.Test;
import org.junit.Rule;
import org.junit.rules.Timeout;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import java.lang.Class;
import java.lang.reflect.Method;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Array;
import java.util.Arrays;
import java.util.stream.Stream;
import java.util.stream.Collectors;
import static org.apache.commons.collections.map.ReflectionUtils.*;
import static org.junit.Assert.assertTrue;
import static org.apache.commons.collections.map.EqualityUtils.*;
import java.lang.Object;
import java.util.LinkedHashMap;

public class CaseInsensitiveMap_init_638985562113 {
    @Rule public Timeout globalTimeout = new Timeout(10, TimeUnit.SECONDS);
     Object term19933;
     Object term20045;
     Object term20049;

    public CaseInsensitiveMap_init_638985562113() {
    }

    public <T> T unknown() {
        throw new IllegalStateException();
    }

    @Before
    public void setup() throws Throwable {
        Object term19873 = newInstance(Class.forName("org.apache.commons.collections.map.CaseInsensitiveMap"));
        setFloatField(term19873, term19873.getClass(), "loadFactor", 0.0F);
        term19933 = new LinkedHashMap();
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        ((LinkedHashMap) term19933).put((Object)null, (Object)null);
        term20045 = newInstance(Class.forName("org.apache.commons.collections.map.CaseInsensitiveMap"));
        Object[] term20046 = (Object[]) newArray("org.apache.commons.collections.map.AbstractHashedMap$HashEntry", 16);
        Object term20047 = newInstance(Class.forName("org.apache.commons.collections.map.AbstractHashedMap$HashEntry"));
        Object term20048 = newInstance(Class.forName("java.lang.Object"));
        setFloatField(term20045, term20045.getClass(), "loadFactor", 0.75F);
        setIntField(term20045, term20045.getClass(), "size", 1);
        setField(term20047, term20047.getClass(), "next", null);
        setField(term20047, term20047.getClass(), "key", term20048);
        setField(term20047, term20047.getClass(), "value", null);
        setElement(term20046, 4, term20047);
        setField(term20045, term20045.getClass(), "data", term20046);
        setIntField(term20045, term20045.getClass(), "threshold", 12);
        setIntField(term20045, term20045.getClass(), "modCount", 1);
        setField(term20045, term20045.getClass(), "entrySet", null);
        setField(term20045, term20045.getClass(), "keySet", null);
        setField(term20045, term20045.getClass(), "values", null);
        setField(term20045, term20045.getClass(), "keySet", null);
        setField(term20045, term20045.getClass(), "values", null);
        term20049 = new LinkedHashMap();
    }

    @Test
    public void test() throws Throwable, Throwable {
        Class<?> klass = Class.forName("org.apache.commons.collections.map.CaseInsensitiveMap");
        Class<?>[] argTypes = new Class<?>[1];
        argTypes[0] = Class.forName("java.util.Map");
        Object[] args = new Object[1];
        args[0] = term19933;
        Object instance = callConstructor(klass, argTypes, args);
        assertTrue(recursiveEquals(instance, term20045));
        assertTrue(recursiveEquals(term19933, term20049));
    }

};


